[build]
  base = "site"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/mattslist"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

[[redirects]]
  from = "/mattslist/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

[[redirects]]
  from = "/mattslist-admin"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

[[redirects]]
  from = "/mattslist-auth/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

[[redirects]]
  from = "/api/sale/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true
